services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./api/:/app
      - ./api/node_modules:/app/node_modules
    ports:
      - "4000:4000"
    env_file:
     - ./api/.env
    networks:
      - internal
  
  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    env_file:
      - ./database/postgres.env
    networks:
      - internal
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  internal:
    driver: bridge

volumes:
  pg-data: